name: Build and Upload Artifacts

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: linux-x64
            os: ubuntu-latest
            arch: x64
          - name: linux-arm64
            os: ubuntu-latest
            arch: arm64
          - name: linux-arm64-termux
            os: ubuntu-latest
            arch: arm64
          - name: windows-x64
            os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          architecture: 'x64'

      - name: Install dependencies
        run: npm install

      - name: Build from TypeScript
        run: npm run build

      - name: Install patchelf (for ARM64 Termux build)
        if: matrix.name == 'linux-arm64-termux'
        run: sudo apt-get update && sudo apt-get install -y patchelf

      - name: Package application
        run: npm run package
        env:
          TARGET_PLATFORM: ${{ matrix.name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ts2cpp-binary-${{ matrix.name }}
          path: dist-sea/

